name: 'Build Browser Extension'

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-extension:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'ubuntu-22.04'
            args: ''

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@a90bcbc6539c36a85cdfeb73f7e2f433735f215b # v2.15.0
        with:
          egress-policy: audit

      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4.3.1
      - name: setup node
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22
      - run: npm install --global --force corepack@latest && corepack enable && corepack prepare pnpm@10.10.0 --activate
      - name: install app dependencies and build it
        working-directory: ./packages/browser-extension
        run: pnpm install
      - name: cleanup
        run: |
          rm postcss.config.js
      - name: build
        working-directory: ./packages/browser-extension
        run: |
          TARGET=chrome pnpm build && cd ./dist && zip -r ../extension.chrome.zip . && cd .. && rm -rf dist
          TARGET=firefox pnpm build && cd ./dist && zip -r ../extension.firefox.zip . && cd .. && rm -rf dist
      - name: upload chrome extension
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: chrome-extension
          path: |
            ./packages/browser-extension/extension.chrome.zip
      - name: upload firefox extension
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: firefox-extension
          path: |
            ./packages/browser-extension/extension.firefox.zip

